version: '3.7'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=restaurant-report
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: